name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.1.1
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
